import React from 'react'
import stuff from './Images/tablet.jpg'


const Home = () => {
  function ScrollToTop(){
    window.scrollTo({
      top: '0',
      behavior: 'smooth'
      
    })
  }
  return (
    <div>
      <h2>
        Lorem ipsum dolor, sit amet consectetur adipisicing elit. Saepe debitis
        eaque in quia ullam nostrum animi distinctio delectus voluptate modi quo
        aut, recusandae eos nam suscipit dolorum odit odio alias placeat minus
        aperiam vel temporibus explicabo. Dolor repudiandae dolores dolorum
        animi ab cum quis, quidem aliquid corrupti similique fugiat commodi
        voluptates maiores accusamus consectetur iusto, facilis itaque. Quia
        aperiam dignissimos corrupti repellendus quisquam ab adipisci odit eum
        dicta, necessitatibus cumque laudantium eveniet, sapiente repudiandae
        quae ea voluptas sit consequuntur maiores nulla earum assumenda
        reprehenderit vel debitis! Hic a alias laborum velit in maxime ut
        exercitationem asperiores repudiandae? Sed, quo temporibus!
      </h2>
      <h2>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab voluptates nostrum, delectus soluta dolores tempora voluptas odio veniam porro provident odit inventore a. Voluptatibus rem nulla eum! Similique inventore quo fugit consectetur eum nisi dolor quos, nostrum tempora eius labore ad alias ea molestiae soluta consequatur deleniti commodi? Odio, amet vitae. Nisi ipsa enim totam nihil. Natus consequatur nisi possimus corporis, inventore eaque minima maiores quae debitis illum veniam nihil labore dolorum vitae aut assumenda placeat sunt sed sapiente dolor quod consectetur! Iusto blanditiis aliquam nesciunt, libero aut quas incidunt nemo eum delectus? Libero illo assumenda exercitationem, temporibus nesciunt dignissimos!</h2>
      <h2>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Aut corporis ipsa dicta voluptatem, quas numquam. Quibusdam, consequatur! Voluptatem, enim obcaecati! Ut dicta quod vitae similique suscipit nesciunt quaerat explicabo, quibusdam quo quia odit, atque totam velit! Eos doloremque quia fugiat distinctio facere quibusdam vel sequi maxime, hic debitis nesciunt commodi quasi sapiente, unde eligendi corrupti id. Dolorem quidem in beatae optio vero ullam provident. Perferendis veniam fuga obcaecati deserunt, dolorum et aliquam autem eveniet quia. Voluptatem incidunt quam illum sit consequuntur quasi impedit excepturi aut mollitia! Eaque magnam iusto ullam, nobis reprehenderit tempore debitis velit dolores unde nemo perspiciatis aspernatur, suscipit consequatur maiores itaque eveniet commodi delectus necessitatibus libero consectetur esse, id voluptas quos aliquid? Nihil quaerat eos repellat doloribus sint, molestias dignissimos labore ex aliquam nemo at iusto necessitatibus excepturi officiis dicta neque autem, ratione rerum sunt nostrum culpa asperiores quia? Nisi, tenetur voluptatem aperiam quia magnam quisquam cumque, ipsum harum error consectetur illo cum! Unde, nulla dolor. Exercitationem iusto nobis ratione, laboriosam fugit quod quia beatae? Earum est placeat pariatur, mollitia eum tenetur praesentium dolorum possimus magni neque saepe in ipsum blanditiis adipisci quisquam exercitationem consectetur vitae libero qui reiciendis nulla eos iusto? Eius delectus totam nulla porro.</h2>
      <h2>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolores voluptatum aspernatur error quia nesciunt ipsam debitis delectus aliquid fugit dicta excepturi consequuntur repellendus incidunt accusamus beatae dignissimos minus voluptatibus amet, totam perspiciatis magnam! Nisi, quibusdam ea eos culpa eligendi fugit soluta ab a tempore nesciunt hic deserunt quaerat minima veritatis laudantium ducimus quas adipisci ratione facere doloremque. Fuga, vitae! Distinctio maxime laboriosam eligendi nisi iste illum sit libero blanditiis, veniam magni, quae illo aliquid neque nihil necessitatibus eaque odio in quod. Quasi impedit incidunt reprehenderit non quis molestiae earum, mollitia sunt inventore repellat debitis laboriosam, nostrum, tempora aliquam molestias ab quam fugiat quas suscipit! Quaerat ab deserunt quas libero non recusandae provident nobis culpa officiis. Suscipit quibusdam maxime sed distinctio vel exercitationem illum ab rerum cum numquam minus ratione magni repellendus, laborum dicta laudantium ipsum minima porro vero totam impedit iusto doloribus nam. Ratione molestiae aspernatur inventore sequi voluptatem repellendus harum laboriosam facere unde recusandae, corrupti, similique veritatis perferendis nam, quae hic necessitatibus repellat illum dolores repudiandae! Distinctio deleniti inventore reiciendis sint ea? Obcaecati assumenda eligendi reprehenderit sunt nam ipsum dolore saepe nihil recusandae esse quaerat quos, qui tempore! Sed modi sapiente accusamus quisquam numquam eligendi voluptas distinctio dolorem voluptatum reiciendis laboriosam molestiae minus unde animi, quia, quidem, veniam iste accusantium inventore eius optio consequatur laudantium similique exercitationem! Temporibus, illo veritatis? Et hic atque quidem aut maxime rerum doloremque nostrum voluptatibus assumenda quibusdam laborum dolor nemo itaque, voluptas quasi ducimus aliquam laboriosam adipisci dicta odit sapiente dolores? Ut fugiat debitis error sunt ullam saepe vel pariatur vitae a temporibus et repellat delectus animi deserunt cupiditate nisi expedita velit dolor modi, beatae nostrum sint. Voluptatum saepe commodi eveniet odit, libero aliquam distinctio quibusdam, aperiam quas, nobis dicta sit cumque animi unde et! Eaque ducimus beatae quaerat voluptatem! Dicta quia cupiditate repudiandae.</h2>
      <h2>lorem400</h2>
      <div>
        <h2>Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis quidem excepturi adipisci! Beatae error exercitationem totam tempora accusamus repudiandae quos debitis doloribus quisquam pariatur nesciunt illum unde saepe dolorum ea animi facere qui aliquam, enim nobis molestias earum quam veritatis distinctio! Vero pariatur reprehenderit repudiandae eaque nulla fugiat, accusantium incidunt hic commodi! Commodi facilis perferendis sint explicabo animi et, dolorem tenetur vel ullam vitae quas placeat sed nobis totam? Tenetur necessitatibus laboriosam deserunt quos quis. Magnam enim, nihil hic, temporibus reiciendis perferendis mollitia iste dolores dolorum nesciunt quae? Delectus enim corporis sunt possimus fuga ab mollitia provident cupiditate voluptatem. Est veniam cum accusantium iure dolorem facere rem harum ea, numquam quae, provident illum eligendi non repellat quis, quod nostrum. Eos necessitatibus culpa cupiditate fuga laboriosam, temporibus ad quasi, perferendis amet sapiente alias neque incidunt, repellat vel molestias eligendi! Illo explicabo itaque reprehenderit similique facere iste facilis quis. Quo sint fuga nihil debitis, illum perspiciatis ipsam et. Quae illo consequatur ipsam voluptatem vero repellendus optio dolorum ad voluptate, aspernatur voluptatibus architecto. Ratione iste eius similique consequatur esse quo! Officiis eum quasi blanditiis iure natus tenetur molestias esse ipsa! Ipsam exercitationem praesentium architecto aut, adipisci ratione quod iusto necessitatibus sit voluptatem nostrum saepe esse omnis officia sint pariatur maiores cupiditate sunt natus commodi? In culpa enim deleniti quaerat obcaecati architecto error reiciendis similique alias necessitatibus veniam quae numquam magnam natus, perferendis quod nihil aliquam, aliquid iste dolore, velit cum ea saepe consequatur! Velit consequatur, explicabo totam asperiores ducimus aut voluptatibus animi praesentium, quia sunt quos. Doloremque assumenda ratione hic! Esse nobis harum reprehenderit omnis, ipsam consequatur nam deserunt error ex? Ut deleniti perferendis, cum aperiam minus voluptates. Sint vero soluta obcaecati sequi quibusdam ipsa, ipsum esse minus consequatur tempore at quas harum sapiente nemo iure veniam, omnis doloremque atque odio totam vel.</h2>
      </div>
      <h2>
        Lorem ipsum dolor, sit amet consectetur adipisicing elit. Saepe debitis
        eaque in quia ullam nostrum animi distinctio delectus voluptate modi quo
        aut, recusandae eos nam suscipit dolorum odit odio alias placeat minus
        aperiam vel temporibus explicabo. Dolor repudiandae dolores dolorum
        animi ab cum quis, quidem aliquid corrupti similique fugiat commodi
        voluptates maiores accusamus consectetur iusto, facilis itaque. Quia
        aperiam dignissimos corrupti repellendus quisquam ab adipisci odit eum
        dicta, necessitatibus cumque laudantium eveniet, sapiente repudiandae
        quae ea voluptas sit consequuntur maiores nulla earum assumenda
        reprehenderit vel debitis! Hic a alias laborum velit in maxime ut
        exercitationem asperiores repudiandae? Sed, quo temporibus!
      </h2>
      <h2>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab voluptates nostrum, delectus soluta dolores tempora voluptas odio veniam porro provident odit inventore a. Voluptatibus rem nulla eum! Similique inventore quo fugit consectetur eum nisi dolor quos, nostrum tempora eius labore ad alias ea molestiae soluta consequatur deleniti commodi? Odio, amet vitae. Nisi ipsa enim totam nihil. Natus consequatur nisi possimus corporis, inventore eaque minima maiores quae debitis illum veniam nihil labore dolorum vitae aut assumenda placeat sunt sed sapiente dolor quod consectetur! Iusto blanditiis aliquam nesciunt, libero aut quas incidunt nemo eum delectus? Libero illo assumenda exercitationem, temporibus nesciunt dignissimos!</h2>
      <h2>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Aut corporis ipsa dicta voluptatem, quas numquam. Quibusdam, consequatur! Voluptatem, enim obcaecati! Ut dicta quod vitae similique suscipit nesciunt quaerat explicabo, quibusdam quo quia odit, atque totam velit! Eos doloremque quia fugiat distinctio facere quibusdam vel sequi maxime, hic debitis nesciunt commodi quasi sapiente, unde eligendi corrupti id. Dolorem quidem in beatae optio vero ullam provident. Perferendis veniam fuga obcaecati deserunt, dolorum et aliquam autem eveniet quia. Voluptatem incidunt quam illum sit consequuntur quasi impedit excepturi aut mollitia! Eaque magnam iusto ullam, nobis reprehenderit tempore debitis velit dolores unde nemo perspiciatis aspernatur, suscipit consequatur maiores itaque eveniet commodi delectus necessitatibus libero consectetur esse, id voluptas quos aliquid? Nihil quaerat eos repellat doloribus sint, molestias dignissimos labore ex aliquam nemo at iusto necessitatibus excepturi officiis dicta neque autem, ratione rerum sunt nostrum culpa asperiores quia? Nisi, tenetur voluptatem aperiam quia magnam quisquam cumque, ipsum harum error consectetur illo cum! Unde, nulla dolor. Exercitationem iusto nobis ratione, laboriosam fugit quod quia beatae? Earum est placeat pariatur, mollitia eum tenetur praesentium dolorum possimus magni neque saepe in ipsum blanditiis adipisci quisquam exercitationem consectetur vitae libero qui reiciendis nulla eos iusto? Eius delectus totam nulla porro.</h2>
      <h2>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolores voluptatum aspernatur error quia nesciunt ipsam debitis delectus aliquid fugit dicta excepturi consequuntur repellendus incidunt accusamus beatae dignissimos minus voluptatibus amet, totam perspiciatis magnam! Nisi, quibusdam ea eos culpa eligendi fugit soluta ab a tempore nesciunt hic deserunt quaerat minima veritatis laudantium ducimus quas adipisci ratione facere doloremque. Fuga, vitae! Distinctio maxime laboriosam eligendi nisi iste illum sit libero blanditiis, veniam magni, quae illo aliquid neque nihil necessitatibus eaque odio in quod. Quasi impedit incidunt reprehenderit non quis molestiae earum, mollitia sunt inventore repellat debitis laboriosam, nostrum, tempora aliquam molestias ab quam fugiat quas suscipit! Quaerat ab deserunt quas libero non recusandae provident nobis culpa officiis. Suscipit quibusdam maxime sed distinctio vel exercitationem illum ab rerum cum numquam minus ratione magni repellendus, laborum dicta laudantium ipsum minima porro vero totam impedit iusto doloribus nam. Ratione molestiae aspernatur inventore sequi voluptatem repellendus harum laboriosam facere unde recusandae, corrupti, similique veritatis perferendis nam, quae hic necessitatibus repellat illum dolores repudiandae! Distinctio deleniti inventore reiciendis sint ea? Obcaecati assumenda eligendi reprehenderit sunt nam ipsum dolore saepe nihil recusandae esse quaerat quos, qui tempore! Sed modi sapiente accusamus quisquam numquam eligendi voluptas distinctio dolorem voluptatum reiciendis laboriosam molestiae minus unde animi, quia, quidem, veniam iste accusantium inventore eius optio consequatur laudantium similique exercitationem! Temporibus, illo veritatis? Et hic atque quidem aut maxime rerum doloremque nostrum voluptatibus assumenda quibusdam laborum dolor nemo itaque, voluptas quasi ducimus aliquam laboriosam adipisci dicta odit sapiente dolores? Ut fugiat debitis error sunt ullam saepe vel pariatur vitae a temporibus et repellat delectus animi deserunt cupiditate nisi expedita velit dolor modi, beatae nostrum sint. Voluptatum saepe commodi eveniet odit, libero aliquam distinctio quibusdam, aperiam quas, nobis dicta sit cumque animi unde et! Eaque ducimus beatae quaerat voluptatem! Dicta quia cupiditate repudiandae.</h2>
      <h2>lorem400</h2>
      <div>
        <h2>Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis quidem excepturi adipisci! Beatae error exercitationem totam tempora accusamus repudiandae quos debitis doloribus quisquam pariatur nesciunt illum unde saepe dolorum ea animi facere qui aliquam, enim nobis molestias earum quam veritatis distinctio! Vero pariatur reprehenderit repudiandae eaque nulla fugiat, accusantium incidunt hic commodi! Commodi facilis perferendis sint explicabo animi et, dolorem tenetur vel ullam vitae quas placeat sed nobis totam? Tenetur necessitatibus laboriosam deserunt quos quis. Magnam enim, nihil hic, temporibus reiciendis perferendis mollitia iste dolores dolorum nesciunt quae? Delectus enim corporis sunt possimus fuga ab mollitia provident cupiditate voluptatem. Est veniam cum accusantium iure dolorem facere rem harum ea, numquam quae, provident illum eligendi non repellat quis, quod nostrum. Eos necessitatibus culpa cupiditate fuga laboriosam, temporibus ad quasi, perferendis amet sapiente alias neque incidunt, repellat vel molestias eligendi! Illo explicabo itaque reprehenderit similique facere iste facilis quis. Quo sint fuga nihil debitis, illum perspiciatis ipsam et. Quae illo consequatur ipsam voluptatem vero repellendus optio dolorum ad voluptate, aspernatur voluptatibus architecto. Ratione iste eius similique consequatur esse quo! Officiis eum quasi blanditiis iure natus tenetur molestias esse ipsa! Ipsam exercitationem praesentium architecto aut, adipisci ratione quod iusto necessitatibus sit voluptatem nostrum saepe esse omnis officia sint pariatur maiores cupiditate sunt natus commodi? In culpa enim deleniti quaerat obcaecati architecto error reiciendis similique alias necessitatibus veniam quae numquam magnam natus, perferendis quod nihil aliquam, aliquid iste dolore, velit cum ea saepe consequatur! Velit consequatur, explicabo totam asperiores ducimus aut voluptatibus animi praesentium, quia sunt quos. Doloremque assumenda ratione hic! Esse nobis harum reprehenderit omnis, ipsam consequatur nam deserunt error ex? Ut deleniti perferendis, cum aperiam minus voluptates. Sint vero soluta obcaecati sequi quibusdam ipsa, ipsum esse minus consequatur tempore at quas harum sapiente nemo iure veniam, omnis doloremque atque odio totam vel.</h2>
      </div>
      <h2>
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Esse molestiae est quaerat excepturi sequi corrupti nesciunt sapiente natus quis facilis tempora similique ab animi eligendi, eum, repellendus suscipit quam ullam expedita? Voluptatibus, laboriosam culpa. Quam sit enim, tempore incidunt quisquam dolore mollitia doloremque fugiat eligendi pariatur eum deleniti porro? Excepturi labore, architecto minus velit ut debitis, impedit quis odit beatae quas ex quae in iste at sit aliquam, illum blanditiis delectus! Placeat alias minima cupiditate omnis ad in cum, iure consequuntur obcaecati facere maxime iste eos! Illum vitae eaque blanditiis laboriosam. Incidunt deleniti eaque eveniet omnis vel alias quos temporibus labore saepe expedita est sequi quis dolores reiciendis earum sapiente laborum voluptates fugiat in, nulla quasi accusantium fugit eligendi aliquam. Dicta, odit corporis dolorem quam distinctio, inventore rem odio aspernatur ipsam optio maxime sequi, temporibus minus minima sit? Incidunt suscipit tempora rem totam temporibus adipisci sunt ipsum dolorum neque repellendus animi laboriosam placeat exercitationem beatae cupiditate vel consequuntur omnis, assumenda in praesentium officia at ducimus natus dolorem. Odit mollitia, non nihil dolorum vitae soluta eos accusantium odio repudiandae maiores asperiores omnis sapiente dignissimos id debitis dolore repellat obcaecati rerum necessitatibus earum, itaque saepe! Dolorum voluptatum impedit, fuga tenetur expedita reiciendis at! Explicabo quisquam ut nesciunt iusto. Temporibus dicta quisquam assumenda ut accusantium quas ex, ipsa voluptates molestiae quos doloribus necessitatibus? Repellendus recusandae ut sit natus eligendi in optio aperiam accusamus veniam vel! Inventore omnis iusto vitae veniam soluta atque assumenda, velit tenetur sapiente recusandae, fugit cum? Excepturi suscipit minima soluta, unde perspiciatis accusantium labore totam laboriosam dignissimos nulla amet placeat quia repellat impedit eos repellendus aperiam doloremque delectus consequuntur ullam rem. Voluptatem harum ratione iusto nobis. Iste fugiat esse nemo quae quibusdam quisquam doloremque hic neque dolorem illum quasi nesciunt explicabo magnam, unde voluptatem maiores molestias repellendus quod alias consectetur.
      </h2>
      <h2>Lorem ipsum dolor sit amet consectetur adipisicing elit. Suscipit ex ratione quasi, iusto sequi quisquam quaerat qui! Eveniet iure perferendis ducimus at ipsa, dolores officia iusto nostrum? Vel neque perferendis tempora. Dignissimos laboriosam consequatur aliquid ut eum assumenda quos, minus ullam fugiat deserunt quis et optio aperiam quae vitae sed, quasi error facere exercitationem quisquam iure accusantium sit, rerum facilis. Et vitae adipisci recusandae commodi, blanditiis quas obcaecati qui esse. A excepturi molestiae veritatis, nesciunt vel consequatur quis? Beatae nisi voluptas et ullam possimus, deleniti incidunt exercitationem, odit recusandae doloribus ex? Fugit ullam illum excepturi reprehenderit maiores architecto voluptatum, ad temporibus pariatur nulla harum. Optio placeat minus sed obcaecati excepturi magnam quis, asperiores aspernatur unde reiciendis sapiente ducimus quod et eveniet beatae nam autem ullam delectus atque nobis, dolor dolore assumenda ipsa. Itaque doloribus, saepe doloremque alias quibusdam iure iste reprehenderit, voluptatibus rem id quo nobis nam aperiam amet fugit sed ut numquam ab ipsa? Illum, iure corrupti! Error maxime vel nulla ad! Illum laudantium iste ipsa dolores. Expedita incidunt itaque nihil. Voluptates, laudantium maiores. Quis iure at placeat, voluptatum numquam ex necessitatibus doloribus! Saepe voluptatibus deserunt aperiam laborum dolore adipisci omnis quibusdam iste excepturi quasi distinctio, iusto rem dicta pariatur repudiandae! Ab excepturi perspiciatis atque ea odit, fugiat laboriosam. Non iste illo veniam ad repellat ea, nihil qui, incidunt quas sed placeat tenetur porro saepe modi maxime ipsam perspiciatis soluta. Voluptas quisquam dolore quibusdam mollitia odit molestias facilis excepturi, ad amet sed ratione minima commodi repudiandae blanditiis nesciunt ex quidem consectetur possimus aliquam iusto ipsa! Aut repudiandae, perspiciatis fugiat voluptates pariatur quos inventore quis cum expedita nesciunt recusandae ducimus quibusdam dolor quia. Labore nobis modi voluptatem, debitis quisquam itaque impedit voluptatum. Officia laboriosam sint ullam a amet suscipit, in dolorum sit ab ipsam eos eum omnis. Nisi, beatae placeat!</h2>
      <i onClick={ScrollToTop} class='fa-solid fa-5x left fa-chevron-up'></i>
    </div>
  )
}

export default Home